eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/

server:
  port: 8081
spring:
  application:
    name: user-service

redis:
  host: localhost
  port: 6379